definitions:
  company.CompanyRetrieveDto:
    properties:
      siren:
        type: string
      siret:
        type: string
    required:
    - siren
    - siret
    type: object
  ginresponse.JsonFormatterSwag:
    properties:
      data:
        type: object
      error:
        type: object
      message:
        type: string
      meta:
        $ref: '#/definitions/ginresponse.JsonSwagMeta'
    type: object
  ginresponse.JsonSwagMeta:
    properties:
      method:
        type: string
      path:
        type: string
      status:
        type: integer
      timestamp:
        type: string
    type: object
info:
  contact: {}
  description: API service tenjin api
  title: tenjin api
  version: "1.0"
paths:
  /company/retrieve-infos:
    post:
      consumes:
      - application/json
      description: Utilise l'API INSEE pour retrouver les informations d'une entreprise
      parameters:
      - description: SIRET et SIREN de l'entreprise
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/company.CompanyRetrieveDto'
      produces:
      - application/json
      responses:
        "200":
          description: Entreprise trouvée
          schema:
            $ref: '#/definitions/ginresponse.JsonFormatterSwag'
        "400":
          description: Paramètres invalides
          schema:
            $ref: '#/definitions/ginresponse.JsonFormatterSwag'
        "500":
          description: Erreur interne lors de l'appel à l'API INSEE
          schema:
            $ref: '#/definitions/ginresponse.JsonFormatterSwag'
      summary: Récupère les infos d'une entreprise via SIRET/SIREN
      tags:
      - company
schemes:
- https
securityDefinitions:
  BearerAuth:
    in: headers
    name: Authorization
    type: apiKey
swagger: "2.0"
