definitions:
  ginresponse.JsonFormatterSwag:
    properties:
      data:
        type: object
      error:
        type: object
      message:
        type: string
      meta:
        $ref: '#/definitions/ginresponse.JsonSwagMeta'
    type: object
  ginresponse.JsonSwagMeta:
    properties:
      method:
        type: string
      path:
        type: string
      status:
        type: integer
      timestamp:
        type: string
    type: object
  insee.CompanyCreateDto:
    properties:
      address:
        type: string
      business_name:
        type: string
      city:
        type: string
      siret:
        type: string
      zip_code:
        type: string
    required:
    - address
    - business_name
    - city
    - siret
    - zip_code
    type: object
info:
  contact: {}
  description: API service tenjin api
  title: tenjin api
  version: "1.0"
paths:
  /company/create:
    post:
      consumes:
      - application/json
      description: Permet de créer une nouvelle company
      parameters:
      - description: Informations de la company à créer
        in: body
        name: company
        required: true
        schema:
          $ref: '#/definitions/insee.CompanyCreateDto'
      produces:
      - application/json
      responses:
        "201":
          description: Company créée avec succès
          schema:
            $ref: '#/definitions/ginresponse.JsonFormatterSwag'
        "400":
          description: Erreur de validation
          schema:
            $ref: '#/definitions/ginresponse.JsonFormatterSwag'
        "500":
          description: Erreur interne
          schema:
            $ref: '#/definitions/ginresponse.JsonFormatterSwag'
      summary: Crée une nouvelle company
      tags:
      - company
schemes:
- https
securityDefinitions:
  BearerAuth:
    in: headers
    name: Authorization
    type: apiKey
swagger: "2.0"
