info:
  contact: {}
  description: API service tenjin api
  title: tenjin api
  version: "1.0"
paths: {}
schemes:
- https
securityDefinitions:
  BearerAuth:
    in: headers
    name: Authorization
    type: apiKey
swagger: "2.0"
