definitions:
  company.CompanyCreateDto:
    properties:
      address:
        type: string
      business_name:
        type: string
      city:
        type: string
      comp_type:
        type: string
      contact_emails:
        items:
          type: string
        type: array
      formations:
        items:
          type: string
        type: array
      sector:
        type: string
      siren:
        type: string
      siret:
        type: string
      users:
        items:
          type: string
        type: array
      zip_code:
        type: string
    required:
    - address
    - business_name
    - city
    - comp_type
    - sector
    - siren
    - siret
    - users
    - zip_code
    type: object
  company.CompanyRetrieveDto:
    properties:
      siren:
        type: string
      siret:
        type: string
    required:
    - siren
    - siret
    type: object
  ginresponse.JsonFormatterSwag:
    properties:
      data:
        type: object
      error:
        type: object
      message:
        type: string
      meta:
        $ref: '#/definitions/ginresponse.JsonSwagMeta'
    type: object
  ginresponse.JsonSwagMeta:
    properties:
      method:
        type: string
      path:
        type: string
      status:
        type: integer
      timestamp:
        type: string
    type: object
info:
  contact: {}
  description: API service tenjin api
  title: tenjin api
  version: "1.0"
paths:
  /company/register:
    post:
      consumes:
      - application/json
      description: Crée une entreprise dans la base de données MongoDB
      parameters:
      - description: Informations de l'entreprise à créer
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/company.CompanyCreateDto'
      produces:
      - application/json
      responses:
        "201":
          description: Entreprise créée
          schema:
            $ref: '#/definitions/ginresponse.JsonFormatterSwag'
        "400":
          description: Paramètres invalides
          schema:
            $ref: '#/definitions/ginresponse.JsonFormatterSwag'
        "500":
          description: Erreur interne lors de la création
          schema:
            $ref: '#/definitions/ginresponse.JsonFormatterSwag'
      summary: Crée une entreprise
      tags:
      - company
  /company/retrieve-infos:
    post:
      consumes:
      - application/json
      description: Utilise l'API INSEE pour retrouver les informations d'une entreprise
      parameters:
      - description: SIRET et SIREN de l'entreprise
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/company.CompanyRetrieveDto'
      produces:
      - application/json
      responses:
        "200":
          description: Entreprise trouvée
          schema:
            $ref: '#/definitions/ginresponse.JsonFormatterSwag'
        "400":
          description: Paramètres invalides
          schema:
            $ref: '#/definitions/ginresponse.JsonFormatterSwag'
        "500":
          description: Erreur interne lors de l'appel à l'API INSEE
          schema:
            $ref: '#/definitions/ginresponse.JsonFormatterSwag'
      summary: Récupère les infos d'une entreprise via SIRET/SIREN
      tags:
      - company
schemes:
- https
securityDefinitions:
  BearerAuth:
    in: headers
    name: Authorization
    type: apiKey
swagger: "2.0"
