name: tenjin-${APP_ENV}
services:
  app:
    build:
      target: ${APP_ENV}
      context: ../app
      dockerfile: ../docker/app.dockerfile
    container_name: tenjin_${APP_ENV}_app
    image: tenjin-app:${APP_ENV}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-nseven"
      - "traefik.http.routers.tenjin-app.rule=${HOST_TRAEFIK_APP}"
      - "traefik.http.routers.tenjin-app.entrypoints=websecure"
      - "traefik.http.routers.tenjin-app.tls=true"
      - "traefik.http.routers.tenjin-app.tls.certresolver=default"
      - "traefik.http.services.tenjin-app.loadbalancer.server.port=${PORT}"
      - "traefik.http.services.tenjin-app.loadbalancer.server.scheme=http"
    volumes:
      - ../app:/app
    env_file:
      - ../app/.env
    networks:
      - traefik-nseven
      - tenjin
    depends_on:
      - api
      - redis

  api:
    build:
      target: ${APP_ENV}
      context: ../back
      dockerfile: ../docker/back.dockerfile
    container_name: tenjin_${APP_ENV}_api
    image: tenjin-api:${APP_ENV}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-nseven"
      - "traefik.http.routers.tenjin-api.rule=${HOST_TRAEFIK_API}"
      - "traefik.http.routers.tenjin-api.entrypoints=websecure"
      - "traefik.http.routers.tenjin-api.tls=true"
      - "traefik.http.routers.tenjin-api.tls.certresolver=default"
      - "traefik.http.services.tenjin-api.loadbalancer.server.port=${PORT}"
      - "traefik.http.services.tenjin-api.loadbalancer.server.scheme=http"
    volumes:
      - ../back:/app
    env_file:
      - ../back/.env
    networks:
      - traefik-nseven
      - tenjin
    depends_on:
      - db
      - redis

  db:
    image: mongo:7
    container_name: tenjin_${APP_ENV}_db
    restart: unless-stopped
    volumes:
      - tenjin_dev_db:/data/db
      - ../docker/mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT_EX:-27017}:27017"
    networks:
      - traefik-nseven
      - tenjin

  redis:
    image: redis:7
    container_name: tenjin_${APP_ENV}_redis
    ports:
      - "6379:6379"
    networks:
      - traefik-nseven
      - tenjin
    restart: unless-stopped

networks:
  traefik-nseven:
    external: true
  tenjin:
    driver: bridge

volumes:
  tenjin_dev_db:
